server:
  port: 8088

# Connection to PostgreSQL database
spring:
  profiles:
    active: native
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_ride
    username: amoloye
    password: adegboola
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


##the active profile is set to native because we want config-server to take configuration from our application,
##if configuration is on git, we name it as git

# swagger
springdoc:
  swagger-ui:
    use-root-path: true
    path: /swagger.html
  api-docs:
    path: /docs