server:
  port: 8060

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/employee/**

management:
  tracing:
    sampling:
      probability: 1.0